import './globals.css'
import React from 'react';
// import { Inter } from 'next/font/google'

// import Navbar from './components/navbar/Navbar';
// import Logo from './components/navbar/Logo';
// import Search from './components/navbar/Search';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({ children }) {
  return (
   
    <html lang="en">
       
      <body >
        {/* <Navbar/> */}
        {/* <Logo/>
        <Search/> */}
        
        {children}</body>
    </html>

  );
}



